version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: ecommerce_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ecommerce_db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Backend API (Docker Hub Image)
  backend:
    image: laxmanadhikari/e-commerce-application-2-tier-architecture:backend
    container_name: ecommerce_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ecommerce_db
      - PORT=3000
      - SESSION_SECRET=secret123
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend (Docker Hub Image)
  frontend:
    image: laxmanadhikari/e-commerce-application-2-tier-architecture:frontend
    container_name: ecommerce_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: